### ISSUE TITLE
The Way marker black square

### ISSUE THREAD

**Issue by Fr33jack** [aronCiucu/DCSTheWay#94] opened 2023-06-04 17:27 UTC
Hi.
The marker to pick a point on the map is inside a black square (see image attached).
I've tried to uninstall/install the app but no effect.
How can i fix this please?
Thanks.
![2023-06-04 201312](https://github.com/aronCiucu/DCSTheWay/assets/125585818/bd0cd80d-9f08-4814-a405-bf8f3fcd0d33)

**Comment by aronCiucu** [comment] 2023-06-18 06:58
Hi, unfortunately I am not able to reproduce this bug on my machine, so if anyone else manages to get this reproduced, let me know and I will try to fix it

**Comment by aronCiucu** [comment] 2023-07-06 10:35
Good news, i think i spotted the issue, it will be fixed with the new release. if it's still not fixed afterwards, reopen the issue

**Closed by aronCiucu** 2023-07-06 10:35 UTC
